---
- hosts: localhost
  tasks: 
    - name: Run sleep.sh
      command: /home/ansadm/sleep.sh
      async: 60
      poll: 0
      delegate_to: localhost
    - name: Install mariadb
      package: 
         name: mariadb
         state: latest
      become: yes
  
