---
- hosts: localhost
  tasks: 
    - name: Run sleep.sh
      command: /home/ansadm/sleep.sh
      async: 60
      poll: 0
      run_once: yes
    - name: install mariadb
      package: 
         name: mariadb
         state: latest
      become: yes
